apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: nunescintia06@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
<<<<<<< HEAD
      nodePort: 31000
=======
      nodePort: 31000 
>>>>>>> 75e6fcc6de7d504b0a08a8360e34aef985e90a13
