apiVersion: v1
kind: Namespace
metadata:
  name: artifactory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:7.6.3 
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: artifactory-data
              mountPath: /var/opt/jfrog/artifactory
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
  namespace: artifactory
spec:
  selector:
    app: artifactory
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

