apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:7.3.6
          ports:
            - containerPort: 8081
          env:
            - name: ARTIFACTORY_LICENSE_FILE
              value: /var/opt/jfrog/artifactory/etc/artifactory.lic
          volumeMounts:
            - name: artifactory-data
              mountPath: /var/opt/jfrog/artifactory
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
spec:
  type: NodePort
  selector:
    app: artifactory
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000 
